# Unverified flatpaks, usually steam related
[managers.flatpak-unverified]
items = [
    "com.fightcade.Fightcade", # Fightcade (competitive retro fighting game emulator
    "com.valvesoftware.Steam", # Steam
    "io.mrarm.mcpelauncher", # Minecraft bedrock launcher
    "com.github.Anuken.Mindustry",
    "org.freedesktop.Platform.VulkanLayer.gamescope/x86_64/24.08", # Gamescope
]

# Gaming utilities in flathub
[managers.flatpak-verified]
items = [
    "com.vysp3r.ProtonPlus", # Proton version manager
    "io.github.Foldex.AdwSteamGtk", # Gnome theme for steam
    "page.kramo.Cartridges", # GTK version of lutris
    "com.dec05eba.gpu_screen_recorder", # Similar to shadowplay
    "com.github.Matoking.protontricks", # Protontricks
    "io.github.wivrn.wivrn", # WiVRn, SteamVR alternative
    "org.prismlauncher.PrismLauncher", # Prism, a minecraft launcher
    "org.vinegarhq.Sober", # Roblox launcher
]
