# CLI utilities via nix

add = "nix profile install nixpkgs##:?"
remove = "nix profile remove #:?"
upgrade = "nix profile upgrade '.*'"

plural_name = "nixpkgs"

hook_name = "nixpkgs"

[config]
many_args = false
