# --------------------- #
#    Generation File    #
# --------------------- #

[managers.soar]
items = [
    "age",
    "asciinema",
    "atuin",
    "babelfish",
    "bat",
    "btop",
    "direnv",
    "eza",
    "fastfetch",
    "fzf",
    "gleam",
    "glow",
    "gum",
    "htop",
    "lazygit",
    "wormhole-rs",
    "mpv",
    "ripgrep",
    "rsync",
    "starship",
    "tldr",
    "tmux",
    "topgrade",
    "up",
    "yazi",
    "zoxide",
]

[managers.brew]
items = [
    "hyfetch",
]

[managers.nixpkgs]
items = [
    "age-plugin-yubikey",
    "autotiling-rs",
    "bat-extras.batman",
    "ncurses",
    "nh",
    "tor-browser",
    "usbtop",
]

[managers.flakes]
items = [
    # "https://codeberg.org/RadioAddition/neovim/archive/main.tar.gz",
]

# Packages to be installed via Flatpak
[managers.flatpak-verified]
items = [
    "ca.desrt.dconf-editor",
    "ca.edestcroix.Recordbox",
    "chat.simplex.simplex",
    "com.github.marhkb.Pods",
    "com.github.tchx84.Flatseal",
    "com.github.wwmm.easyeffects",
    "com.obsproject.Studio",
    "com.usebottles.bottles",
    "im.dino.Dino",
    "io.ente.photos",
    "io.github.dvlv.boxbuddyrs",
    "io.github.flattool.Warehouse",
    "io.github.nozwock.Packet",
    "net.lutris.Lutris",
    "org.gnome.Boxes",
    "org.gnome.Calculator",
    "org.gnome.Extensions",
    "org.gnome.Fractal",
    "org.gnome.Polari",
    "org.gnome.Snapshot",
    "org.gnome.World.PikaBackup",
    "org.gnome.baobab",
    "org.kde.filelight",
    "org.kde.krita",
    "org.keepassxc.KeePassXC",
    "org.libreoffice.LibreOffice",
    "org.moneymanagerex.MMEX",
    "org.nickvision.money",
    "org.nickvision.tubeconverter",
    "org.onionshare.OnionShare",
    "org.openandroidinstaller.OpenAndroidInstaller",
    "org.shotcut.Shotcut",
    "org.sqlitebrowser.sqlitebrowser",
    "org.tenacityaudio.Tenacity",
    "org.torproject.torbrowser-launcher",
]

# Unverified flathub apps
[managers.flatpak-unverified]
items = [
    "au.stevetech.yafi",
    "ch.protonmail.protonmail-bridge",
    "com.google.AndroidStudio",
    "com.yubico.yubioath",
    "org.bleachbit.BleachBit",
    "org.gnome.seahorse.Application",
    "org.musicbrainz.Picard",
    "org.pipewire.Helvum",
    "org.signal.Signal",
]
